### ISSUE TITLE
The private network value should be 172.16.0.0/12

### ISSUE THREAD

**Issue by zx1986** [mrlesmithjr/ansible-squid#28]
https://github.com/mrlesmithjr/ansible-squid/blob/b33cca87bf863eaf548816f88bf823d2a4f61e8c/defaults/main.yml#L29

Maybe just a typo?

refs: https://en.wikipedia.org/wiki/Private_network

**Comment by mrlesmithjr** [comment]
Good catch! PR's are welcomed and encouraged as well.
